# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
    
require_relative 'cval'

def cval_populate(wire_size)
  Cvalue.create(wire_type: 1, conduit_type: 1, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 1, 1))
  Cvalue.create(wire_type: 1, conduit_type: 1, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 1, 2))
  Cvalue.create(wire_type: 1, conduit_type: 2, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 2, 1))
  Cvalue.create(wire_type: 1, conduit_type: 2, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 2, 2))
  Cvalue.create(wire_type: 2, conduit_type: 1, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 1, 1))
  Cvalue.create(wire_type: 2, conduit_type: 1, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 1, 2))
  Cvalue.create(wire_type: 2, conduit_type: 2, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 2, 1))
  Cvalue.create(wire_type: 2, conduit_type: 2, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 2, 2))
end

cval_populate("14")
cval_populate("12")
cval_populate("10")
cval_populate("8")
cval_populate("6")
cval_populate("4")
cval_populate("3")
cval_populate("2")
cval_populate("1")
cval_populate("1/0")
cval_populate("2/0")
cval_populate("3/0")
cval_populate("4/0")
cval_populate("250")
cval_populate("300")
cval_populate("350")
cval_populate("400")
cval_populate("500")
cval_populate("600")
cval_populate("750")
cval_populate("1,000")

DryerDemand.create(count: 1, demand: 1)
DryerDemand.create(count: 2, demand: 1)
DryerDemand.create(count: 3, demand: 1)
DryerDemand.create(count: 4, demand: 1)
DryerDemand.create(count: 5, demand: 0.85)
DryerDemand.create(count: 6, demand: 0.75)
DryerDemand.create(count: 7, demand: 0.65)
DryerDemand.create(count: 8, demand: 0.6)
DryerDemand.create(count: 9, demand: 0.55)
DryerDemand.create(count: 10, demand: 0.5)
DryerDemand.create(count: 11, demand: 0.47)
DryerDemand.create(count: 12, demand: 0.46)
DryerDemand.create(count: 13, demand: 0.45)
DryerDemand.create(count: 14, demand: 0.44)
DryerDemand.create(count: 15, demand: 0.43)
DryerDemand.create(count: 16, demand: 0.42)
DryerDemand.create(count: 17, demand: 0.41)
DryerDemand.create(count: 18, demand: 0.4)
DryerDemand.create(count: 19, demand: 0.39)
DryerDemand.create(count: 20, demand: 0.38)
DryerDemand.create(count: 21, demand: 0.37)
DryerDemand.create(count: 22, demand: 0.36)
DryerDemand.create(count: 23, demand: 0.35)
DryerDemand.create(count: 24, demand: 0.345)
DryerDemand.create(count: 25, demand: 0.34)
DryerDemand.create(count: 26, demand: 0.335)
DryerDemand.create(count: 27, demand: 0.33)
DryerDemand.create(count: 28, demand: 0.325)
DryerDemand.create(count: 29, demand: 0.32)
DryerDemand.create(count: 30, demand: 0.315)
DryerDemand.create(count: 31, demand: 0.31)
DryerDemand.create(count: 32, demand: 0.305)
DryerDemand.create(count: 33, demand: 0.3)
DryerDemand.create(count: 34, demand: 0.295)
DryerDemand.create(count: 35, demand: 0.29)
DryerDemand.create(count: 36, demand: 0.285)
DryerDemand.create(count: 37, demand: 0.28)
DryerDemand.create(count: 38, demand: 0.275)
DryerDemand.create(count: 39, demand: 0.27)
DryerDemand.create(count: 40, demand: 0.265)
DryerDemand.create(count: 41, demand: 0.26)
DryerDemand.create(count: 42, demand: 0.255)
DryerDemand.create(count: 43, demand: 0.25)

LoadDemand.create(unit_count: 3, demand: 0.45)
LoadDemand.create(unit_count: 4, demand: 0.45)
LoadDemand.create(unit_count: 5, demand: 0.45)
LoadDemand.create(unit_count: 6, demand: 0.44)
LoadDemand.create(unit_count: 7, demand: 0.44)
LoadDemand.create(unit_count: 8, demand: 0.43)
LoadDemand.create(unit_count: 9, demand: 0.43)
LoadDemand.create(unit_count: 10, demand: 0.43)
LoadDemand.create(unit_count: 11, demand: 0.42)
LoadDemand.create(unit_count: 12, demand: 0.41)
LoadDemand.create(unit_count: 13, demand: 0.41)
LoadDemand.create(unit_count: 14, demand: 0.4)
LoadDemand.create(unit_count: 15, demand: 0.4)
LoadDemand.create(unit_count: 16, demand: 0.39)
LoadDemand.create(unit_count: 17, demand: 0.39)
LoadDemand.create(unit_count: 18, demand: 0.38)
LoadDemand.create(unit_count: 19, demand: 0.38)
LoadDemand.create(unit_count: 20, demand: 0.38)
LoadDemand.create(unit_count: 21, demand: 0.37)
LoadDemand.create(unit_count: 22, demand: 0.36)
LoadDemand.create(unit_count: 23, demand: 0.36)
LoadDemand.create(unit_count: 24, demand: 0.35)
LoadDemand.create(unit_count: 25, demand: 0.35)
LoadDemand.create(unit_count: 26, demand: 0.34)
LoadDemand.create(unit_count: 27, demand: 0.34)
LoadDemand.create(unit_count: 28, demand: 0.33)
LoadDemand.create(unit_count: 29, demand: 0.33)
LoadDemand.create(unit_count: 30, demand: 0.33)
LoadDemand.create(unit_count: 31, demand: 0.32)
LoadDemand.create(unit_count: 32, demand: 0.31)
LoadDemand.create(unit_count: 33, demand: 0.31)
LoadDemand.create(unit_count: 34, demand: 0.3)
LoadDemand.create(unit_count: 35, demand: 0.3)
LoadDemand.create(unit_count: 36, demand: 0.3)
LoadDemand.create(unit_count: 37, demand: 0.29)
LoadDemand.create(unit_count: 38, demand: 0.29)
LoadDemand.create(unit_count: 39, demand: 0.28)
LoadDemand.create(unit_count: 40, demand: 0.28)
LoadDemand.create(unit_count: 41, demand: 0.28)
LoadDemand.create(unit_count: 42, demand: 0.28)
LoadDemand.create(unit_count: 43, demand: 0.27)
LoadDemand.create(unit_count: 44, demand: 0.27)
LoadDemand.create(unit_count: 45, demand: 0.27)
LoadDemand.create(unit_count: 46, demand: 0.26)
LoadDemand.create(unit_count: 47, demand: 0.26)
LoadDemand.create(unit_count: 48, demand: 0.26)
LoadDemand.create(unit_count: 49, demand: 0.26)
LoadDemand.create(unit_count: 50, demand: 0.26)
LoadDemand.create(unit_count: 51, demand: 0.25)
LoadDemand.create(unit_count: 52, demand: 0.25)
LoadDemand.create(unit_count: 53, demand: 0.25)
LoadDemand.create(unit_count: 54, demand: 0.25)
LoadDemand.create(unit_count: 55, demand: 0.25)
LoadDemand.create(unit_count: 56, demand: 0.24)
LoadDemand.create(unit_count: 57, demand: 0.24)
LoadDemand.create(unit_count: 58, demand: 0.24)
LoadDemand.create(unit_count: 59, demand: 0.24)
LoadDemand.create(unit_count: 60, demand: 0.24)
LoadDemand.create(unit_count: 61, demand: 0.24)
LoadDemand.create(unit_count: 62, demand: 0.23)