# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
    
require_relative 'cval'

def cval_populate(wire_size)
  Cvalue.create(wire_type: 1, conduit_type: 1, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 1, 1))
  Cvalue.create(wire_type: 1, conduit_type: 1, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 1, 2))
  Cvalue.create(wire_type: 1, conduit_type: 2, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 2, 1))
  Cvalue.create(wire_type: 1, conduit_type: 2, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 1, 2, 2))
  Cvalue.create(wire_type: 2, conduit_type: 1, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 1, 1))
  Cvalue.create(wire_type: 2, conduit_type: 1, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 1, 2))
  Cvalue.create(wire_type: 2, conduit_type: 2, runs_type: 1, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 2, 1))
  Cvalue.create(wire_type: 2, conduit_type: 2, runs_type: 2, wire_size: wire_size, c_value: c_val_picker(wire_size, 2, 2, 2))
end

cval_populate("14")
cval_populate("12")
cval_populate("10")
cval_populate("8")
cval_populate("6")
cval_populate("4")
cval_populate("3")
cval_populate("2")
cval_populate("1")
cval_populate("1/0")
cval_populate("2/0")
cval_populate("3/0")
cval_populate("4/0")
cval_populate("250")
cval_populate("300")
cval_populate("350")
cval_populate("400")
cval_populate("500")
cval_populate("600")
cval_populate("750")
cval_populate("1,000")

DryerDemand.create(count: 1, demand: 1)
DryerDemand.create(count: 2, demand: 1)
DryerDemand.create(count: 3, demand: 1)
DryerDemand.create(count: 4, demand: 1)
DryerDemand.create(count: 5, demand: 0.85)
DryerDemand.create(count: 6, demand: 0.75)
DryerDemand.create(count: 7, demand: 0.65)
DryerDemand.create(count: 8, demand: 0.6)
DryerDemand.create(count: 9, demand: 0.55)
DryerDemand.create(count: 10, demand: 0.5)
DryerDemand.create(count: 11, demand: 0.47)
DryerDemand.create(count: 12, demand: 0.46)
DryerDemand.create(count: 13, demand: 0.45)
DryerDemand.create(count: 14, demand: 0.44)
DryerDemand.create(count: 15, demand: 0.43)
DryerDemand.create(count: 16, demand: 0.42)
DryerDemand.create(count: 17, demand: 0.41)
DryerDemand.create(count: 18, demand: 0.4)
DryerDemand.create(count: 19, demand: 0.39)
DryerDemand.create(count: 20, demand: 0.38)
DryerDemand.create(count: 21, demand: 0.37)
DryerDemand.create(count: 22, demand: 0.36)
DryerDemand.create(count: 23, demand: 0.35)
DryerDemand.create(count: 24, demand: 0.345)
DryerDemand.create(count: 25, demand: 0.34)
DryerDemand.create(count: 26, demand: 0.335)
DryerDemand.create(count: 27, demand: 0.33)
DryerDemand.create(count: 28, demand: 0.325)
DryerDemand.create(count: 29, demand: 0.32)
DryerDemand.create(count: 30, demand: 0.315)
DryerDemand.create(count: 31, demand: 0.31)
DryerDemand.create(count: 32, demand: 0.305)
DryerDemand.create(count: 33, demand: 0.3)
DryerDemand.create(count: 34, demand: 0.295)
DryerDemand.create(count: 35, demand: 0.29)
DryerDemand.create(count: 36, demand: 0.285)
DryerDemand.create(count: 37, demand: 0.28)
DryerDemand.create(count: 38, demand: 0.275)
DryerDemand.create(count: 39, demand: 0.27)
DryerDemand.create(count: 40, demand: 0.265)
DryerDemand.create(count: 41, demand: 0.26)
DryerDemand.create(count: 42, demand: 0.255)
DryerDemand.create(count: 43, demand: 0.25)

LoadDemand.create(unit_count: 3, demand: 0.45)
LoadDemand.create(unit_count: 4, demand: 0.45)
LoadDemand.create(unit_count: 5, demand: 0.45)
LoadDemand.create(unit_count: 6, demand: 0.44)
LoadDemand.create(unit_count: 7, demand: 0.44)
LoadDemand.create(unit_count: 8, demand: 0.43)
LoadDemand.create(unit_count: 9, demand: 0.43)
LoadDemand.create(unit_count: 10, demand: 0.43)
LoadDemand.create(unit_count: 11, demand: 0.42)
LoadDemand.create(unit_count: 12, demand: 0.41)
LoadDemand.create(unit_count: 13, demand: 0.41)
LoadDemand.create(unit_count: 14, demand: 0.4)
LoadDemand.create(unit_count: 15, demand: 0.4)
LoadDemand.create(unit_count: 16, demand: 0.39)
LoadDemand.create(unit_count: 17, demand: 0.39)
LoadDemand.create(unit_count: 18, demand: 0.38)
LoadDemand.create(unit_count: 19, demand: 0.38)
LoadDemand.create(unit_count: 20, demand: 0.38)
LoadDemand.create(unit_count: 21, demand: 0.37)
LoadDemand.create(unit_count: 22, demand: 0.36)
LoadDemand.create(unit_count: 23, demand: 0.36)
LoadDemand.create(unit_count: 24, demand: 0.35)
LoadDemand.create(unit_count: 25, demand: 0.35)
LoadDemand.create(unit_count: 26, demand: 0.34)
LoadDemand.create(unit_count: 27, demand: 0.34)
LoadDemand.create(unit_count: 28, demand: 0.33)
LoadDemand.create(unit_count: 29, demand: 0.33)
LoadDemand.create(unit_count: 30, demand: 0.33)
LoadDemand.create(unit_count: 31, demand: 0.32)
LoadDemand.create(unit_count: 32, demand: 0.31)
LoadDemand.create(unit_count: 33, demand: 0.31)
LoadDemand.create(unit_count: 34, demand: 0.3)
LoadDemand.create(unit_count: 35, demand: 0.3)
LoadDemand.create(unit_count: 36, demand: 0.3)
LoadDemand.create(unit_count: 37, demand: 0.29)
LoadDemand.create(unit_count: 38, demand: 0.29)
LoadDemand.create(unit_count: 39, demand: 0.28)
LoadDemand.create(unit_count: 40, demand: 0.28)
LoadDemand.create(unit_count: 41, demand: 0.28)
LoadDemand.create(unit_count: 42, demand: 0.28)
LoadDemand.create(unit_count: 43, demand: 0.27)
LoadDemand.create(unit_count: 44, demand: 0.27)
LoadDemand.create(unit_count: 45, demand: 0.27)
LoadDemand.create(unit_count: 46, demand: 0.26)
LoadDemand.create(unit_count: 47, demand: 0.26)
LoadDemand.create(unit_count: 48, demand: 0.26)
LoadDemand.create(unit_count: 49, demand: 0.26)
LoadDemand.create(unit_count: 50, demand: 0.26)
LoadDemand.create(unit_count: 51, demand: 0.25)
LoadDemand.create(unit_count: 52, demand: 0.25)
LoadDemand.create(unit_count: 53, demand: 0.25)
LoadDemand.create(unit_count: 54, demand: 0.25)
LoadDemand.create(unit_count: 55, demand: 0.25)
LoadDemand.create(unit_count: 56, demand: 0.24)
LoadDemand.create(unit_count: 57, demand: 0.24)
LoadDemand.create(unit_count: 58, demand: 0.24)
LoadDemand.create(unit_count: 59, demand: 0.24)
LoadDemand.create(unit_count: 60, demand: 0.24)
LoadDemand.create(unit_count: 61, demand: 0.24)
LoadDemand.create(unit_count: 62, demand: 0.23)

#Volt Drop Copper

Voltdrop.create(wire_size: "14", wire_type: 0, conduit: 0, phase: 0, power_factor: 4371)
Voltdrop.create(wire_size: "14", wire_type: 0, conduit: 0, phase: 1, power_factor: 5047)
Voltdrop.create(wire_size: "14", wire_type: 0, conduit: 1, phase: 0, power_factor: 4355)
Voltdrop.create(wire_size: "14", wire_type: 0, conduit: 1, phase: 1, power_factor: 5029)

Voltdrop.create(wire_size: "12", wire_type: 0, conduit: 0, phase: 0, power_factor: 2841)
Voltdrop.create(wire_size: "12", wire_type: 0, conduit: 0, phase: 1, power_factor: 3281)
Voltdrop.create(wire_size: "12", wire_type: 0, conduit: 1, phase: 0, power_factor: 2827)
Voltdrop.create(wire_size: "12", wire_type: 0, conduit: 1, phase: 1, power_factor: 3264)

Voltdrop.create(wire_size: "10", wire_type: 0, conduit: 0, phase: 0, power_factor: 1728)
Voltdrop.create(wire_size: "10", wire_type: 0, conduit: 0, phase: 1, power_factor: 1995)
Voltdrop.create(wire_size: "10", wire_type: 0, conduit: 1, phase: 0, power_factor: 1714)
Voltdrop.create(wire_size: "10", wire_type: 0, conduit: 1, phase: 1, power_factor: 1980)

Voltdrop.create(wire_size: "8", wire_type: 0, conduit: 0, phase: 0, power_factor: 1148)
Voltdrop.create(wire_size: "8", wire_type: 0, conduit: 0, phase: 1, power_factor: 1326)
Voltdrop.create(wire_size: "8", wire_type: 0, conduit: 1, phase: 0, power_factor: 1134)
Voltdrop.create(wire_size: "8", wire_type: 0, conduit: 1, phase: 1, power_factor: 1310)

Voltdrop.create(wire_size: "6", wire_type: 0, conduit: 0, phase: 0, power_factor: 745)
Voltdrop.create(wire_size: "6", wire_type: 0, conduit: 0, phase: 1, power_factor: 860)
Voltdrop.create(wire_size: "6", wire_type: 0, conduit: 1, phase: 0, power_factor: 731)
Voltdrop.create(wire_size: "6", wire_type: 0, conduit: 1, phase: 1, power_factor: 845)

Voltdrop.create(wire_size: "4", wire_type: 0, conduit: 0, phase: 0, power_factor: 491)
Voltdrop.create(wire_size: "4", wire_type: 0, conduit: 0, phase: 1, power_factor: 568)
Voltdrop.create(wire_size: "4", wire_type: 0, conduit: 1, phase: 0, power_factor: 479)
Voltdrop.create(wire_size: "4", wire_type: 0, conduit: 1, phase: 1, power_factor: 553)

Voltdrop.create(wire_size: "3", wire_type: 0, conduit: 0, phase: 0, power_factor: 407)
Voltdrop.create(wire_size: "3", wire_type: 0, conduit: 0, phase: 1, power_factor: 470)
Voltdrop.create(wire_size: "3", wire_type: 0, conduit: 1, phase: 0, power_factor: 395)
Voltdrop.create(wire_size: "3", wire_type: 0, conduit: 1, phase: 1, power_factor: 456)

Voltdrop.create(wire_size: "2", wire_type: 0, conduit: 0, phase: 0, power_factor: 336)
Voltdrop.create(wire_size: "2", wire_type: 0, conduit: 0, phase: 1, power_factor: 388)
Voltdrop.create(wire_size: "2", wire_type: 0, conduit: 1, phase: 0, power_factor: 310)
Voltdrop.create(wire_size: "2", wire_type: 0, conduit: 1, phase: 1, power_factor: 358)

Voltdrop.create(wire_size: "1", wire_type: 0, conduit: 0, phase: 0, power_factor: 280)
Voltdrop.create(wire_size: "1", wire_type: 0, conduit: 0, phase: 1, power_factor: 324)
Voltdrop.create(wire_size: "1", wire_type: 0, conduit: 1, phase: 0, power_factor: 255)
Voltdrop.create(wire_size: "1", wire_type: 0, conduit: 1, phase: 1, power_factor: 295)

Voltdrop.create(wire_size: "1/0", wire_type: 0, conduit: 0, phase: 0, power_factor: 223)
Voltdrop.create(wire_size: "1/0", wire_type: 0, conduit: 0, phase: 1, power_factor: 258)
Voltdrop.create(wire_size: "1/0", wire_type: 0, conduit: 1, phase: 0, power_factor: 212)
Voltdrop.create(wire_size: "1/0", wire_type: 0, conduit: 1, phase: 1, power_factor: 244)

Voltdrop.create(wire_size: "2/0", wire_type: 0, conduit: 0, phase: 0, power_factor: 194)
Voltdrop.create(wire_size: "2/0", wire_type: 0, conduit: 0, phase: 1, power_factor: 224)
Voltdrop.create(wire_size: "2/0", wire_type: 0, conduit: 1, phase: 0, power_factor: 183)
Voltdrop.create(wire_size: "2/0", wire_type: 0, conduit: 1, phase: 1, power_factor: 211)

Voltdrop.create(wire_size: "3/0", wire_type: 0, conduit: 0, phase: 0, power_factor: 163)
Voltdrop.create(wire_size: "3/0", wire_type: 0, conduit: 0, phase: 1, power_factor: 188)
Voltdrop.create(wire_size: "3/0", wire_type: 0, conduit: 1, phase: 0, power_factor: 150)
Voltdrop.create(wire_size: "3/0", wire_type: 0, conduit: 1, phase: 1, power_factor: 173)

Voltdrop.create(wire_size: "4/0", wire_type: 0, conduit: 0, phase: 0, power_factor: 140)
Voltdrop.create(wire_size: "4/0", wire_type: 0, conduit: 0, phase: 1, power_factor: 162)
Voltdrop.create(wire_size: "4/0", wire_type: 0, conduit: 1, phase: 0, power_factor: 128)
Voltdrop.create(wire_size: "4/0", wire_type: 0, conduit: 1, phase: 1, power_factor: 148)

Voltdrop.create(wire_size: "250", wire_type: 0, conduit: 0, phase: 0, power_factor: 128)
Voltdrop.create(wire_size: "250", wire_type: 0, conduit: 0, phase: 1, power_factor: 148)
Voltdrop.create(wire_size: "250", wire_type: 0, conduit: 1, phase: 0, power_factor: 114)
Voltdrop.create(wire_size: "250", wire_type: 0, conduit: 1, phase: 1, power_factor: 132)

Voltdrop.create(wire_size: "300", wire_type: 0, conduit: 0, phase: 0, power_factor: 115)
Voltdrop.create(wire_size: "300", wire_type: 0, conduit: 0, phase: 1, power_factor: 133)
Voltdrop.create(wire_size: "300", wire_type: 0, conduit: 1, phase: 0, power_factor: 103)
Voltdrop.create(wire_size: "300", wire_type: 0, conduit: 1, phase: 1, power_factor: 119)

Voltdrop.create(wire_size: "350", wire_type: 0, conduit: 0, phase: 0, power_factor: 106)
Voltdrop.create(wire_size: "350", wire_type: 0, conduit: 0, phase: 1, power_factor: 122)
Voltdrop.create(wire_size: "350", wire_type: 0, conduit: 1, phase: 0, power_factor: 94)
Voltdrop.create(wire_size: "350", wire_type: 0, conduit: 1, phase: 1, power_factor: 108)

Voltdrop.create(wire_size: "400", wire_type: 0, conduit: 0, phase: 0, power_factor: 99)
Voltdrop.create(wire_size: "400", wire_type: 0, conduit: 0, phase: 1, power_factor: 114)
Voltdrop.create(wire_size: "400", wire_type: 0, conduit: 1, phase: 0, power_factor: 87)
Voltdrop.create(wire_size: "400", wire_type: 0, conduit: 1, phase: 1, power_factor: 100)

Voltdrop.create(wire_size: "500", wire_type: 0, conduit: 0, phase: 0, power_factor: 90)
Voltdrop.create(wire_size: "500", wire_type: 0, conduit: 0, phase: 1, power_factor: 104)
Voltdrop.create(wire_size: "500", wire_type: 0, conduit: 1, phase: 0, power_factor: 77)
Voltdrop.create(wire_size: "500", wire_type: 0, conduit: 1, phase: 1, power_factor: 90)

Voltdrop.create(wire_size: "600", wire_type: 0, conduit: 0, phase: 0, power_factor: 84)
Voltdrop.create(wire_size: "600", wire_type: 0, conduit: 0, phase: 1, power_factor: 97)
Voltdrop.create(wire_size: "600", wire_type: 0, conduit: 1, phase: 0, power_factor: 72)
Voltdrop.create(wire_size: "600", wire_type: 0, conduit: 1, phase: 1, power_factor: 83)

Voltdrop.create(wire_size: "750", wire_type: 0, conduit: 0, phase: 0, power_factor: 78)
Voltdrop.create(wire_size: "750", wire_type: 0, conduit: 0, phase: 1, power_factor: 91)
Voltdrop.create(wire_size: "750", wire_type: 0, conduit: 1, phase: 0, power_factor: 65)
Voltdrop.create(wire_size: "750", wire_type: 0, conduit: 1, phase: 1, power_factor: 76)

Voltdrop.create(wire_size: "1,000", wire_type: 0, conduit: 0, phase: 0, power_factor: 72)
Voltdrop.create(wire_size: "1,000", wire_type: 0, conduit: 0, phase: 1, power_factor: 84)
Voltdrop.create(wire_size: "1,000", wire_type: 0, conduit: 1, phase: 0, power_factor: 59)
Voltdrop.create(wire_size: "1,000", wire_type: 0, conduit: 1, phase: 1, power_factor: 68)

#Volt Drop Aluminum

Voltdrop.create(wire_size: "12", wire_type: 1, conduit: 0, phase: 0, power_factor: 4504)
Voltdrop.create(wire_size: "12", wire_type: 1, conduit: 0, phase: 1, power_factor: 5201)
Voltdrop.create(wire_size: "12", wire_type: 1, conduit: 1, phase: 0, power_factor: 4490)
Voltdrop.create(wire_size: "12", wire_type: 1, conduit: 1, phase: 1, power_factor: 5184)

Voltdrop.create(wire_size: "10", wire_type: 1, conduit: 0, phase: 0, power_factor: 2836)
Voltdrop.create(wire_size: "10", wire_type: 1, conduit: 0, phase: 1, power_factor: 3275)
Voltdrop.create(wire_size: "10", wire_type: 1, conduit: 1, phase: 0, power_factor: 2823)
Voltdrop.create(wire_size: "10", wire_type: 1, conduit: 1, phase: 1, power_factor: 3260)

Voltdrop.create(wire_size: "8", wire_type: 1, conduit: 0, phase: 0, power_factor: 1868)
Voltdrop.create(wire_size: "8", wire_type: 1, conduit: 0, phase: 1, power_factor: 2158)
Voltdrop.create(wire_size: "8", wire_type: 1, conduit: 1, phase: 0, power_factor: 1855)
Voltdrop.create(wire_size: "8", wire_type: 1, conduit: 1, phase: 1, power_factor: 2142)

Voltdrop.create(wire_size: "6", wire_type: 1, conduit: 0, phase: 0, power_factor: 1188)
Voltdrop.create(wire_size: "6", wire_type: 1, conduit: 0, phase: 1, power_factor: 1372)
Voltdrop.create(wire_size: "6", wire_type: 1, conduit: 1, phase: 0, power_factor: 1175)
Voltdrop.create(wire_size: "6", wire_type: 1, conduit: 1, phase: 1, power_factor: 1357)

Voltdrop.create(wire_size: "4", wire_type: 1, conduit: 0, phase: 0, power_factor: 769)
Voltdrop.create(wire_size: "4", wire_type: 1, conduit: 0, phase: 1, power_factor: 888)
Voltdrop.create(wire_size: "4", wire_type: 1, conduit: 1, phase: 0, power_factor: 756)
Voltdrop.create(wire_size: "4", wire_type: 1, conduit: 1, phase: 1, power_factor: 873)

Voltdrop.create(wire_size: "3", wire_type: 1, conduit: 0, phase: 0, power_factor: 615)
Voltdrop.create(wire_size: "3", wire_type: 1, conduit: 0, phase: 1, power_factor: 710)
Voltdrop.create(wire_size: "3", wire_type: 1, conduit: 1, phase: 0, power_factor: 603)
Voltdrop.create(wire_size: "3", wire_type: 1, conduit: 1, phase: 1, power_factor: 696)

Voltdrop.create(wire_size: "2", wire_type: 1, conduit: 0, phase: 0, power_factor: 502)
Voltdrop.create(wire_size: "2", wire_type: 1, conduit: 0, phase: 1, power_factor: 580)
Voltdrop.create(wire_size: "2", wire_type: 1, conduit: 1, phase: 0, power_factor: 490)
Voltdrop.create(wire_size: "2", wire_type: 1, conduit: 1, phase: 1, power_factor: 566)

Voltdrop.create(wire_size: "1", wire_type: 1, conduit: 0, phase: 0, power_factor: 405)
Voltdrop.create(wire_size: "1", wire_type: 1, conduit: 0, phase: 1, power_factor: 468)
Voltdrop.create(wire_size: "1", wire_type: 1, conduit: 1, phase: 0, power_factor: 394)
Voltdrop.create(wire_size: "1", wire_type: 1, conduit: 1, phase: 1, power_factor: 455)

Voltdrop.create(wire_size: "1/0", wire_type: 1, conduit: 0, phase: 0, power_factor: 334)
Voltdrop.create(wire_size: "1/0", wire_type: 1, conduit: 0, phase: 1, power_factor: 386)
Voltdrop.create(wire_size: "1/0", wire_type: 1, conduit: 1, phase: 0, power_factor: 322)
Voltdrop.create(wire_size: "1/0", wire_type: 1, conduit: 1, phase: 1, power_factor: 372)

Voltdrop.create(wire_size: "2/0", wire_type: 1, conduit: 0, phase: 0, power_factor: 277)
Voltdrop.create(wire_size: "2/0", wire_type: 1, conduit: 0, phase: 1, power_factor: 320)
Voltdrop.create(wire_size: "2/0", wire_type: 1, conduit: 1, phase: 0, power_factor: 266)
Voltdrop.create(wire_size: "2/0", wire_type: 1, conduit: 1, phase: 1, power_factor: 307)

Voltdrop.create(wire_size: "3/0", wire_type: 1, conduit: 0, phase: 0, power_factor: 234)
Voltdrop.create(wire_size: "3/0", wire_type: 1, conduit: 0, phase: 1, power_factor: 270)
Voltdrop.create(wire_size: "3/0", wire_type: 1, conduit: 1, phase: 0, power_factor: 223)
Voltdrop.create(wire_size: "3/0", wire_type: 1, conduit: 1, phase: 1, power_factor: 258)

Voltdrop.create(wire_size: "4/0", wire_type: 1, conduit: 0, phase: 0, power_factor: 191)
Voltdrop.create(wire_size: "4/0", wire_type: 1, conduit: 0, phase: 1, power_factor: 221)
Voltdrop.create(wire_size: "4/0", wire_type: 1, conduit: 1, phase: 0, power_factor: 181)
Voltdrop.create(wire_size: "4/0", wire_type: 1, conduit: 1, phase: 1, power_factor: 209)

Voltdrop.create(wire_size: "250", wire_type: 1, conduit: 0, phase: 0, power_factor: 173)
Voltdrop.create(wire_size: "250", wire_type: 1, conduit: 0, phase: 1, power_factor: 200)
Voltdrop.create(wire_size: "250", wire_type: 1, conduit: 1, phase: 0, power_factor: 160)
Voltdrop.create(wire_size: "250", wire_type: 1, conduit: 1, phase: 1, power_factor: 185)

Voltdrop.create(wire_size: "300", wire_type: 1, conduit: 0, phase: 0, power_factor: 152)
Voltdrop.create(wire_size: "300", wire_type: 1, conduit: 0, phase: 1, power_factor: 176)
Voltdrop.create(wire_size: "300", wire_type: 1, conduit: 1, phase: 0, power_factor: 140)
Voltdrop.create(wire_size: "300", wire_type: 1, conduit: 1, phase: 1, power_factor: 162)

Voltdrop.create(wire_size: "350", wire_type: 1, conduit: 0, phase: 0, power_factor: 139)
Voltdrop.create(wire_size: "350", wire_type: 1, conduit: 0, phase: 1, power_factor: 160)
Voltdrop.create(wire_size: "350", wire_type: 1, conduit: 1, phase: 0, power_factor: 125)
Voltdrop.create(wire_size: "350", wire_type: 1, conduit: 1, phase: 1, power_factor: 145)

Voltdrop.create(wire_size: "400", wire_type: 1, conduit: 0, phase: 0, power_factor: 127)
Voltdrop.create(wire_size: "400", wire_type: 1, conduit: 0, phase: 1, power_factor: 146)
Voltdrop.create(wire_size: "400", wire_type: 1, conduit: 1, phase: 0, power_factor: 116)
Voltdrop.create(wire_size: "400", wire_type: 1, conduit: 1, phase: 1, power_factor: 134)

Voltdrop.create(wire_size: "500", wire_type: 1, conduit: 0, phase: 0, power_factor: 112)
Voltdrop.create(wire_size: "500", wire_type: 1, conduit: 0, phase: 1, power_factor: 129)
Voltdrop.create(wire_size: "500", wire_type: 1, conduit: 1, phase: 0, power_factor: 100)
Voltdrop.create(wire_size: "500", wire_type: 1, conduit: 1, phase: 1, power_factor: 115)

Voltdrop.create(wire_size: "600", wire_type: 1, conduit: 0, phase: 0, power_factor: 102)
Voltdrop.create(wire_size: "600", wire_type: 1, conduit: 0, phase: 1, power_factor: 118)
Voltdrop.create(wire_size: "600", wire_type: 1, conduit: 1, phase: 0, power_factor: 90)
Voltdrop.create(wire_size: "600", wire_type: 1, conduit: 1, phase: 1, power_factor: 104)

Voltdrop.create(wire_size: "750", wire_type: 1, conduit: 0, phase: 0, power_factor: 92)
Voltdrop.create(wire_size: "750", wire_type: 1, conduit: 0, phase: 1, power_factor: 107)
Voltdrop.create(wire_size: "750", wire_type: 1, conduit: 1, phase: 0, power_factor: 79)
Voltdrop.create(wire_size: "750", wire_type: 1, conduit: 1, phase: 1, power_factor: 92)

Voltdrop.create(wire_size: "1,000", wire_type: 1, conduit: 0, phase: 0, power_factor: 82)
Voltdrop.create(wire_size: "1,000", wire_type: 1, conduit: 0, phase: 1, power_factor: 95)
Voltdrop.create(wire_size: "1,000", wire_type: 1, conduit: 1, phase: 0, power_factor: 70)
Voltdrop.create(wire_size: "1,000", wire_type: 1, conduit: 1, phase: 1, power_factor: 81)